export const AGREGAR_BRUTO = 'AGREGAR_BRUTO';
export const AGREGAR_BRUTO_EXITO = 'AGREGAR_BRUTO_EXITO';
export const AGREGAR_BRUTO_ERROR = 'AGREGAR_BRUTO_ERROR';


export const COMENZAR_DESCARGA_BRUTOS = 'COMENZAR_DESCARGA_BRUTOS';
export const DESCARGA_BRUTOS_EXITO = 'DESCARGA_BRUTOS_EXITO';
export const DESCARGA_BRUTOS_ERROR = 'DESCARGA_BRUTOS_ERROR';