export const AGREGAR_BRUTO = 'AGREGAR_BRUTO';
export const AGREGAR_BRUTO_EXITO = 'AGREGAR_BRUTO_EXITO';
export const AGREGAR_BRUTO_ERROR = 'AGREGAR_BRUTO_ERROR';


export const COMENZAR_DESCARGA_BRUTOS = 'COMENZAR_DESCARGA_BRUTOS';
export const DESCARGA_BRUTOS_EXITO = 'DESCARGA_BRUTOS_EXITO';
export const DESCARGA_BRUTOS_ERROR = 'DESCARGA_BRUTOS_ERROR';


export const OBTENER_BRUTO_ELIMINAR = 'OBTENER_BRUTO_ELIMINAR';
export const BRUTO_ELIMINADO_EXITO = 'BRUTO_ELIMINADO_EXITO';
export const BRUTO_ELIMINADO_ERROR = 'BRUTO_ELIMINADO_ERROR';

export const OBTENER_BRUTO_EDITAR = ' OBTENER_BRUTO_EDITAR';
export const COMENZAR_EDICION_BRUTO = 'COMENZAR_EDICION_BRUTO';
export const BRUTO_EDITADO_EXITO = 'BRUTO_EDITADO_EXITO';
export const BRUTO_EDITADO_ERROR = 'BRUTO_EDITADO_ERROR';